# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email_confirmed',
            new_name='opted_in',
        ),
    ]
