# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160516_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
