# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160517_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
